apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-techchallenge-api
spec:
  selector:
    matchLabels:
      app: techchallenge-api
  template:
    metadata:
      labels:
        app: techchallenge-api
    spec:
      containers:
        - name: techchallenge-api
          image: 802236982505.dkr.ecr.us-east-1.amazonaws.com/techchallenge:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: techchallenge-api-service
spec:
  selector:
    app: techchallenge-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
